export interface ImageItem {
  src: string;
  category: 'animals' | 'vehicles' | 'stories';
}

export const images: ImageItem[] = [
  // stories
  { src: 'story_1.png', category: 'stories' },
  { src: 'story_2.png', category: 'stories' },
  { src: 'story_3.png', category: 'stories' },
  { src: 'story_4.png', category: 'stories' },
  { src: 'story_5.png', category: 'stories' },
  { src: 'Pic1.png', category: 'stories' },
  { src: 'Pic2.png', category: 'stories' },
  { src: 'Pic3.png', category: 'stories' },
  { src: 'Pic4.png', category: 'stories' },
  { src: 'Pic5.png', category: 'stories' },
  { src: 'Pic6.png', category: 'stories' },
  { src: 'girl_playing.png', category: 'stories' },

  // vehicles
  { src: 'car.png', category: 'vehicles' },
  { src: 'car_2.png', category: 'vehicles' },
  { src: 'carr.png', category: 'vehicles' },
  { src: 'carrr.png', category: 'vehicles' },
  { src: '3-enhanced.png', category: 'vehicles' },
  { src: '4-enhanced.png', category: 'vehicles' },
  { src: '5-enhanced.png', category: 'vehicles' },
  { src: '6.png', category: 'vehicles' },
  { src: '7.png', category: 'vehicles' },
  { src: '8.png', category: 'vehicles' },
  { src: '9.png', category: 'vehicles' },
  { src: '10.png', category: 'vehicles' },
  { src: '11-enhanced.png', category: 'vehicles' },
  { src: '12-enhanced.png', category: 'vehicles' },
  { src: '13.png', category: 'vehicles' },
  { src: '14.png', category: 'vehicles' },
  { src: '15.png', category: 'vehicles' },
  { src: 'ar_car_28.png', category: 'vehicles' },
  { src: 'ar_car_29.png', category: 'vehicles' },
  { src: 'ar_car_30.png', category: 'vehicles' },
  { src: 'ar_car_31.png', category: 'vehicles' },
  { src: 'ar_car_32.png', category: 'vehicles' },
  { src: 'ar_car_33.png', category: 'vehicles' },
  { src: 'ar_car_34.png', category: 'vehicles' },
  { src: 'ar_car_35.png', category: 'vehicles' },
  { src: 'ar_car_36.png', category: 'vehicles' },
  { src: 'ar_car_37.png', category: 'vehicles' },
  { src: 'ar_car_38.png', category: 'vehicles' },
  { src: 'ar_car_39.png', category: 'vehicles' },
  { src: 'ar_car_40.png', category: 'vehicles' },
  { src: 'ar_car_41.png', category: 'vehicles' },
  { src: 'ar_car_42.png', category: 'vehicles' },
  { src: 'ar_car_43.png', category: 'vehicles' },
  { src: 'ar_car_44.png', category: 'vehicles' },
  { src: 'ar_car_45.png', category: 'vehicles' },
  { src: 'ar_car_46.png', category: 'vehicles' },
  { src: 'ar_car_47.png', category: 'vehicles' },

  // animals (and others)
  { src: 'baby_tiger.png', category: 'animals' },
  { src: 'bear.png', category: 'animals' },
  { src: 'bunny.png', category: 'animals' },
  { src: 'cat.png', category: 'animals' },
  { src: 'cat_2.png', category: 'animals' },
  { src: 'dinsour.png', category: 'animals' },
  { src: 'girrafe.png', category: 'animals' },
  { src: 'girrafes.png', category: 'animals' },
  { src: 'kwala.png', category: 'animals' },
  { src: 'kwala_2.png', category: 'animals' },
  { src: 'sea_creatures.png', category: 'animals' },
  { src: 'tawoos.png', category: 'animals' },
  { src: 'turtle.png', category: 'animals' },
  { src: 'zoo.png', category: 'animals' },
  { src: 'flowers.png', category: 'animals' },
  { src: 'fungi.png', category: 'animals' },
  { src: '1.png', category: 'animals' },
  { src: '2.png', category: 'animals' },
  { src: 'ar_animal_1.png', category: 'animals' },
  { src: 'ar_animal_2.png', category: 'animals' },
  { src: 'ar_animal_3.png', category: 'animals' },
  { src: 'ar_animal_4.png', category: 'animals' },
  { src: 'ar_animal_5.png', category: 'animals' },
  { src: 'ar_animal_6.png', category: 'animals' },
  { src: 'ar_animal_7.png', category: 'animals' },
  { src: 'ar_animal_8.png', category: 'animals' },
  { src: 'ar_animal_9.png', category: 'animals' },
  { src: 'ar_animal_10.png', category: 'animals' },
  { src: 'ar_animal_11.png', category: 'animals' },
  { src: 'ar_animal_12.png', category: 'animals' },
  { src: 'ar_animal_13.png', category: 'animals' },
  { src: 'ar_animal_14.png', category: 'animals' },
  { src: 'ar_animal_15.png', category: 'animals' },
  { src: 'ar_animal_16.png', category: 'animals' },
  { src: 'ar_animal_17.png', category: 'animals' },
  { src: 'ar_animal_18.png', category: 'animals' },
  { src: 'ar_animal_19.png', category: 'animals' },
  { src: 'ar_animal_20.png', category: 'animals' },
  { src: 'ar_animal_21.png', category: 'animals' },
  { src: 'ar_animal_22.png', category: 'animals' },
  { src: 'ar_animal_23.png', category: 'animals' },
  { src: 'ar_animal_24.png', category: 'animals' },
  { src: 'ar_animal_25.png', category: 'animals' },
  { src: 'ar_animal_26.png', category: 'animals' },
  { src: 'ar_animal_27.png', category: 'animals' },
  { src: 'ar_animal_28.png', category: 'animals' },
];
